### ISSUE TITLE
v2.1 deployed as release

### ISSUE THREAD

**Issue by lucasmellos** [SonarOpenCommunity/sonar-cxx#2450]
Can v2.1 be deployed as a release? It breaks the sonarqube helm chart everytime a new release is update on snapshot

**Comment by guwirth** [comment]
Hi @lucasmellos,

im not familiar with this helm chart. What exactly is the issue? From build and test perspective it’s exactly the same except there is no GitHub release. 

Regards,

**Comment by lucasmellos** [comment]
hi @guwirth the problem is that there's some kinda cronjob that fetches the URL that we put on the file (the JAR URL) and every time you push a new release to snapshot, the old version is excluded. 

For example: 
```yaml
  plugins:
    install:
      - https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/latest-snapshot/sonar-cxx-plugin-2.1.0.349.jar
    lib:
      - sonar-cxx-plugin-2.1.0.349.jar
```

as soon you update the snapshot, the URL becomes broken because we won't have access to 2.1.0.349, only 2.1.0.350 and it'll break the chart making us upgrade the chart every time you push a new release. 

A more fixed release would be very great.
